services:
  portal-gluetun:
    image: qmcgaw/gluetun:v3.40.3
    container_name: portal-gluetun
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    security_opt:
      - no-new-privileges:true
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - TZ=Europe/Warsaw
      - FIREWALL=on
      - FIREWALL_INPUT_PORTS=443,80
      - DOT=on
      - DOT_PROVIDERS=cloudflare
      - HEALTH_VPN_DURATION_INITIAL=30s
      - PUBLICIP_ENABLED=off
    volumes:
      - ./gluetun:/gluetun
      - ./gluetun/wg0.conf:/gluetun/wireguard/wg0.conf:ro  # I keep this hardlinked with various wg conf files
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    networks:
      - portal-proxy
    healthcheck:
      test: ["CMD", "/gluetun-entrypoint", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  portal-nginx:
    image: nginx:1.29-alpine
    container_name: portal-nginx
    depends_on:
      portal-gluetun:
        condition: service_healthy
    # Share gluetun's network namespace: all traffic goes through VPN
    network_mode: "service:portal-gluetun"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
      - CHOWN
    read_only: true
    tmpfs:
      - /var/cache/nginx
      - /var/run

networks:
  portal-proxy:
    driver: bridge
